name: test_app_wiggli
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.5
  fpdart: ^1.1.0
  hooks_riverpod: ^2.5.1
  toastification: ^1.2.1
  #riverpod_lint: ^2.3.10
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  freezed_annotation: ^2.4.1
  logger: ^2.1.0
  flutter_screenutil: ^5.9.0
  #flutter_svg: ^2.0.10+1
  flex_color_scheme: ^7.3.1
  auto_route: ^7.9.2

  path_provider: ^2.1.2
  dio: ^5.4.1
  flutter_svg: ^2.0.10+1
  awesome_bottom_bar: ^1.2.4
  collection: ^1.18.0
  fdottedline_nullsafety: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.6.4
  isar_generator: ^3.1.0+1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  envied_generator: ^0.5.3
  flutter_gen_runner: ^5.4.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lint: ^2.3.0

flutter_gen:
  assets:
    enabled: true
  fonts:
    enabled: true
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/png/
    - assets/icons/svg/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
